export const FOODS = [
  {
    name: "규카츠",
    countryType: "japanese",
    ingredient: "meat",
    fried: "fried",
    src: "/src/assets/규카츠.jpeg",
  },
  {
    name: "야키토리",
    countryType: "japanese",
    ingredient: "meat",
    fried: "nonFried",
    src: "/src/assets/야키토리.jpeg",
  },
  {
    name: "새우튀김",
    countryType: "japanese",
    ingredient: "seafood",
    fried: "fried",
    src: "/src/assets/새우튀김.jpeg",
  },
  {
    name: "모둠 사시미",
    countryType: "japanese",
    ingredient: "seafood",
    fried: "nonFried",
    src: "/src/assets/모둠사시미.jpeg",
  },
  {
    name: "덴뿌라",
    countryType: "japanese",
    ingredient: "etc",
    fried: "fried",
    src: "/src/assets/덴뿌라.jpeg",
  },
  {
    name: "완두콩",
    countryType: "japanese",
    ingredient: "etc",
    fried: "nonFried",
    src: "/src/assets/완두콩.jpeg",
  },
  {
    name: "치킨",
    countryType: "korean",
    ingredient: "meat",
    fried: "fried",
    src: "/src/assets/치킨.jpeg",
  },
  {
    name: "삼겹살",
    countryType: "korean",
    ingredient: "meat",
    fried: "nonFried",
    src: "/src/assets/삼겹살.jpeg",
  },
  {
    name: "오징어튀김",
    countryType: "korean",
    ingredient: "seafood",
    fried: "fried",
    src: "/src/assets/오징어튀김.jpeg",
  },
  {
    name: "연포탕",
    countryType: "korean",
    ingredient: "seafood",
    fried: "nonFried",
    src: "/src/assets/연포탕.jpeg",
  },
  {
    name: "닭껍질튀김",
    countryType: "korean",
    ingredient: "etc",
    fried: "fried",
    src: "/src/assets/닭껍질튀김.jpeg",
  },
  {
    name: "김&땅콩",
    countryType: "korean",
    ingredient: "etc",
    fried: "nonFried",
    src: "/src/assets/김과자.jpeg",
  },
  {
    name: "꿔바로우",
    countryType: "chinese",
    ingredient: "meat",
    fried: "fried",
    src: "/src/assets/꿔바로우.jpeg",
  },
  {
    name: "양꼬치",
    countryType: "chinese",
    ingredient: "meat",
    fried: "nonFried",
    src: "/src/assets/양꼬치.jpeg",
  },
  {
    name: "새우 춘권",
    countryType: "chinese",
    ingredient: "seafood",
    fried: "fried",
    src: "/src/assets/새우춘권.jpeg",
  },
  {
    name: "해물짬뽕",
    countryType: "chinese",
    ingredient: "seafood",
    fried: "nonFried",
    src: "/src/assets/해물짬뽕.jpeg",
  },
  {
    name: "두부튀김",
    countryType: "chinese",
    ingredient: "etc",
    fried: "fried",
    src: "/src/assets/두부튀김.jpeg",
  },
  {
    name: "딤섬",
    countryType: "chinese",
    ingredient: "etc",
    fried: "nonFried",
    src: "/src/assets/딤섬.jpeg",
  },
];
